using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum BuffType
{
    NONE = 0,
    BUFFTYPE_HP,
    BUFFTYPE_MINATTACKPOWER,
    BUFFTYPE_MAXATTACKPOWER,
    BUFFTYPE_DEFENCE,
    BUFFTYPE_ATTACKSPEED,
    BUFFTYPE_ATTACKDISTANCE,
    BUFFTYPE_CRITICALPERCENT,
    BUFFTYPE_CRITICALATTACKPOWER,
    BUFFTYPE_MOVESPEED,
    BUFFTYPE_JUMPPOWER,
    BUFFTYPE_PEREIVE,
    BUFFTYPE_WEAPONTIME
}